title: LYCHEE GARDEN
page-top-title: Welcome to LYCHEE GARDEN
top-section-bg-text: Salvation lies within
home-subtitle: 李致远&ensp;|&ensp;同济
copyright-text: '&copy; lychee-garden 2023-2025. All Rights Reserved.'
